// Tamil word bank — each word has Tamil script, tanglish spellings, and English meaning
// All tanglish variants are lowercased for matching

export const WORDS = [
  // ═══════════════════ விலங்குகள் (Animals) ═══════════════════
  { id: 'elephant', tamil: 'யானை', tanglish: ['yaanai', 'yanai', 'aanai', 'ayanai'], english: 'elephant', category: 'animals', difficulty: 'easy' },
  { id: 'tiger', tamil: 'புலி', tanglish: ['puli', 'pooli', 'poouli'], english: 'tiger', category: 'animals', difficulty: 'easy' },
  { id: 'lion', tamil: 'சிங்கம்', tanglish: ['singam', 'singham', 'singm'], english: 'lion', category: 'animals', difficulty: 'easy' },
  { id: 'monkey', tamil: 'குரங்கு', tanglish: ['kurangu', 'korangu', 'urangu'], english: 'monkey', category: 'animals', difficulty: 'easy' },
  { id: 'fish', tamil: 'மீன்', tanglish: ['meen', 'min', 'meen'], english: 'fish', category: 'animals', difficulty: 'easy' },
  { id: 'dog', tamil: 'நாய்', tanglish: ['naai', 'nai', 'naay'], english: 'dog', category: 'animals', difficulty: 'easy' },
  { id: 'cat', tamil: 'பூனை', tanglish: ['poonai', 'punai', 'puni', 'poonni'], english: 'cat', category: 'animals', difficulty: 'easy' },
  { id: 'horse', tamil: 'குதிரை', tanglish: ['kuthirai', 'kudurai', 'kuthurai', 'kuttirai'], english: 'horse', category: 'animals', difficulty: 'medium' },
  { id: 'cow', tamil: 'மாடு', tanglish: ['maadu', 'maatu', 'madu', 'maaddu'], english: 'cow', category: 'animals', difficulty: 'easy' },
  { id: 'goat', tamil: 'ஆடு', tanglish: ['aadu', 'aatu', 'aadu'], english: 'goat', category: 'animals', difficulty: 'easy' },
  { id: 'chicken', tamil: 'கோழி', tanglish: ['kozhi', 'koli', 'gozhi', 'koozhi'], english: 'chicken', category: 'animals', difficulty: 'easy' },
  { id: 'duck', tamil: 'வாத்து', tanglish: ['vaathu', 'vaattu', 'wathu', 'vathu'], english: 'duck', category: 'animals', difficulty: 'easy' },
  { id: 'eagle', tamil: 'கழுகு', tanglish: ['kazhugu', 'kazugu', 'kalugu', 'kazhukku'], english: 'eagle', category: 'animals', difficulty: 'medium' },
  { id: 'snake', tamil: 'பாம்பு', tanglish: ['pambu', 'paambu', 'paambhu', 'pamb'], english: 'snake', category: 'animals', difficulty: 'easy' },
  { id: 'rabbit', tamil: 'முயல்', tanglish: ['muyalu', 'muyal', 'muyel', 'mooyal'], english: 'rabbit', category: 'animals', difficulty: 'easy' },
  { id: 'fox', tamil: 'நரி', tanglish: ['nari', 'neri', 'narii'], english: 'fox', category: 'animals', difficulty: 'easy' },
  { id: 'bear', tamil: 'கரடி', tanglish: ['karadi', 'kaadi', 'kardi', 'karradi'], english: 'bear', category: 'animals', difficulty: 'easy' },
  { id: 'camel', tamil: 'ஒட்டகம்', tanglish: ['ottakam', 'oottakam', 'ottakm'], english: 'camel', category: 'animals', difficulty: 'medium' },
  { id: 'deer', tamil: 'மான்', tanglish: ['maan', 'man', 'maann'], english: 'deer', category: 'animals', difficulty: 'easy' },
  { id: 'parrot', tamil: 'கிளி', tanglish: ['kili', 'keeli', 'kiili'], english: 'parrot', category: 'animals', difficulty: 'easy' },
  { id: 'crow', tamil: 'காகம்', tanglish: ['kaagam', 'kagam', 'kakkam', 'kaakam'], english: 'crow', category: 'animals', difficulty: 'easy' },
  { id: 'peacock', tamil: 'மயில்', tanglish: ['mayil', 'muyil', 'mayil'], english: 'peacock', category: 'animals', difficulty: 'easy' },
  { id: 'ant', tamil: 'எறும்பு', tanglish: ['erumbu', 'irumbu', 'erombu', 'yirumbu'], english: 'ant', category: 'animals', difficulty: 'easy' },
  { id: 'frog', tamil: 'தவளை', tanglish: ['thavalay', 'thavalai', 'thavlai', 'tavalai'], english: 'frog', category: 'animals', difficulty: 'easy' },
  { id: 'elephant_baby', tamil: 'கன்று', tanglish: ['kanru', 'kanrru', 'kandu'], english: 'calf', category: 'animals', difficulty: 'medium' },
  { id: 'sparrow', tamil: 'சிட்டுக்குருவி', tanglish: ['chittu kuruvi', 'chittukuruvi', 'sittu kuruvi'], english: 'sparrow', category: 'animals', difficulty: 'hard' },
  { id: 'mosquito', tamil: 'கொசு', tanglish: ['kosu', 'goshu', 'kosu'], english: 'mosquito', category: 'animals', difficulty: 'easy' },
  { id: 'butterfly', tamil: 'வண்ணத்துப்பூச்சி', tanglish: ['vannathu puchi', 'vannapu puchi', 'butterfly'], english: 'butterfly', category: 'animals', difficulty: 'hard' },
  { id: 'crab', tamil: 'நண்டு', tanglish: ['nandu', 'nantu', 'nanthu'], english: 'crab', category: 'animals', difficulty: 'easy' },
  { id: 'buffalo', tamil: 'எருமை', tanglish: ['erumai', 'irumi', 'erumi'], english: 'buffalo', category: 'animals', difficulty: 'medium' },

  // ═══════════════════ உணவு (Food) ═══════════════════
  { id: 'idli', tamil: 'இட்லி', tanglish: ['idli', 'ittli', 'iddly', 'idly'], english: 'idli', category: 'food', difficulty: 'easy' },
  { id: 'dosa', tamil: 'தோசை', tanglish: ['dosai', 'thosai', 'dosa', 'dosaa'], english: 'dosa', category: 'food', difficulty: 'easy' },
  { id: 'sambar', tamil: 'சாம்பார்', tanglish: ['sambar', 'sambhar', 'saambar', 'chambar'], english: 'sambar', category: 'food', difficulty: 'easy' },
  { id: 'rasam', tamil: 'ரசம்', tanglish: ['rasam', 'rasam', 'raasam', 'rasm'], english: 'rasam', category: 'food', difficulty: 'easy' },
  { id: 'biryani', tamil: 'பிரியாணி', tanglish: ['biryani', 'biriyani', 'briyani', 'biriyanee'], english: 'biryani', category: 'food', difficulty: 'easy' },
  { id: 'vadai', tamil: 'வடை', tanglish: ['vadai', 'vada', 'vaday', 'vadaa'], english: 'vada', category: 'food', difficulty: 'easy' },
  { id: 'pongal', tamil: 'பொங்கல்', tanglish: ['pongal', 'pongal', 'pongall'], english: 'pongal', category: 'food', difficulty: 'easy' },
  { id: 'appam', tamil: 'அப்பம்', tanglish: ['appam', 'apam', 'appum'], english: 'appam', category: 'food', difficulty: 'easy' },
  { id: 'mango', tamil: 'மாம்பழம்', tanglish: ['mambazham', 'maampazham', 'mampazhm', 'mango'], english: 'mango', category: 'food', difficulty: 'easy' },
  { id: 'banana', tamil: 'வாழைப்பழம்', tanglish: ['vaazhaipazham', 'vaalaippazham', 'vaazhai', 'banana'], english: 'banana', category: 'food', difficulty: 'medium' },
  { id: 'rice', tamil: 'சோறு', tanglish: ['soru', 'choru', 'soro'], english: 'rice', category: 'food', difficulty: 'easy' },
  { id: 'milk', tamil: 'பால்', tanglish: ['paal', 'pal', 'paall'], english: 'milk', category: 'food', difficulty: 'easy' },
  { id: 'water', tamil: 'தண்ணீர்', tanglish: ['thanneer', 'tanneer', 'thaneer', 'tani'], english: 'water', category: 'food', difficulty: 'easy' },
  { id: 'tea', tamil: 'தேநீர்', tanglish: ['theneer', 'tea', 'chai', 'chaaya', 'chaay'], english: 'tea', category: 'food', difficulty: 'easy' },
  { id: 'coffee', tamil: 'காபி', tanglish: ['kaapi', 'kapi', 'coffee', 'kaappe'], english: 'coffee', category: 'food', difficulty: 'easy' },
  { id: 'halwa', tamil: 'அல்வா', tanglish: ['halwa', 'alva', 'alwa', 'halva'], english: 'halwa', category: 'food', difficulty: 'easy' },
  { id: 'payasam', tamil: 'பாயசம்', tanglish: ['payasam', 'paaysam', 'paayasam', 'kheer'], english: 'payasam', category: 'food', difficulty: 'easy' },
  { id: 'murukku', tamil: 'முறுக்கு', tanglish: ['murukku', 'muruku', 'murukku', 'murukk'], english: 'murukku', category: 'food', difficulty: 'easy' },
  { id: 'fish_curry', tamil: 'மீன் குழம்பு', tanglish: ['meen kuzhambu', 'meen kulambu', 'meen gravy'], english: 'fish curry', category: 'food', difficulty: 'medium' },
  { id: 'tamarind', tamil: 'புளி', tanglish: ['puli', 'pooli', 'pully'], english: 'tamarind', category: 'food', difficulty: 'easy' },
  { id: 'coconut', tamil: 'தேங்காய்', tanglish: ['theengai', 'thengai', 'thegai', 'coconut'], english: 'coconut', category: 'food', difficulty: 'easy' },
  { id: 'onion', tamil: 'வெங்காயம்', tanglish: ['vengayam', 'vengaayam', 'onion'], english: 'onion', category: 'food', difficulty: 'easy' },
  { id: 'tomato', tamil: 'தக்காளி', tanglish: ['thakkali', 'takkali', 'tomato'], english: 'tomato', category: 'food', difficulty: 'easy' },
  { id: 'puttu', tamil: 'புட்டு', tanglish: ['puttu', 'putu', 'poottu'], english: 'puttu', category: 'food', difficulty: 'easy' },
  { id: 'kozhukattai', tamil: 'கொழுக்கட்டை', tanglish: ['kozhukattai', 'kodukkadai', 'kozhukkattai'], english: 'kozhukattai', category: 'food', difficulty: 'hard' },

  // ═══════════════════ பொருட்கள் (Objects) ═══════════════════
  { id: 'tree', tamil: 'மரம்', tanglish: ['maram', 'marum'], english: 'tree', category: 'objects', difficulty: 'easy' },
  { id: 'house', tamil: 'வீடு', tanglish: ['veedu', 'veetu', 'viidu'], english: 'house', category: 'objects', difficulty: 'easy' },
  { id: 'car', tamil: 'கார்', tanglish: ['kaar', 'car', 'kaaru'], english: 'car', category: 'objects', difficulty: 'easy' },
  { id: 'bicycle', tamil: 'சைக்கிள்', tanglish: ['cycle', 'saikkal', 'saikil', 'saikkiyal'], english: 'bicycle', category: 'objects', difficulty: 'easy' },
  { id: 'book', tamil: 'புத்தகம்', tanglish: ['puthagam', 'puttakam', 'puthakam', 'book'], english: 'book', category: 'objects', difficulty: 'easy' },
  { id: 'pen', tamil: 'பேனா', tanglish: ['pena', 'peena', 'penna', 'pen'], english: 'pen', category: 'objects', difficulty: 'easy' },
  { id: 'glasses', tamil: 'கண்ணாடி', tanglish: ['kannadi', 'kannaadi', 'specs'], english: 'glasses', category: 'objects', difficulty: 'easy' },
  { id: 'door', tamil: 'கதவு', tanglish: ['kathavu', 'katabu', 'katavu', 'kathav'], english: 'door', category: 'objects', difficulty: 'easy' },
  { id: 'window', tamil: 'ஜன்னல்', tanglish: ['jannal', 'jannel', 'jannul'], english: 'window', category: 'objects', difficulty: 'easy' },
  { id: 'chair', tamil: 'நாற்காலி', tanglish: ['naarkali', 'naarkali', 'chair', 'naarkaalee'], english: 'chair', category: 'objects', difficulty: 'easy' },
  { id: 'table', tamil: 'மேசை', tanglish: ['mesai', 'mesa', 'table', 'messai'], english: 'table', category: 'objects', difficulty: 'easy' },
  { id: 'phone', tamil: 'தொலைபேசி', tanglish: ['tholaipesi', 'phone', 'tholai pesi', 'mobile'], english: 'phone', category: 'objects', difficulty: 'easy' },
  { id: 'fan', tamil: 'விசிறி', tanglish: ['fan', 'visiri', 'viciri', 'fan'], english: 'fan', category: 'objects', difficulty: 'easy' },
  { id: 'lamp', tamil: 'விளக்கு', tanglish: ['vilakku', 'vilakku', 'lamp', 'vilak'], english: 'lamp', category: 'objects', difficulty: 'easy' },
  { id: 'umbrella', tamil: 'குடை', tanglish: ['kudai', 'kodai', 'umbrella', 'kuddai'], english: 'umbrella', category: 'objects', difficulty: 'easy' },
  { id: 'bag', tamil: 'பை', tanglish: ['pai', 'bag', 'paai'], english: 'bag', category: 'objects', difficulty: 'easy' },
  { id: 'clock', tamil: 'கடிகாரம்', tanglish: ['kadigaram', 'kedigaram', 'watch', 'clock'], english: 'clock', category: 'objects', difficulty: 'easy' },
  { id: 'key', tamil: 'சாவி', tanglish: ['saavi', 'chaavi', 'key', 'saavee'], english: 'key', category: 'objects', difficulty: 'easy' },
  { id: 'ladder', tamil: 'ஏணி', tanglish: ['yeni', 'eni', 'ladder', 'eeni'], english: 'ladder', category: 'objects', difficulty: 'easy' },
  { id: 'boat', tamil: 'படகு', tanglish: ['padagu', 'paadahu', 'boat', 'padak'], english: 'boat', category: 'objects', difficulty: 'easy' },
  { id: 'ship', tamil: 'கப்பல்', tanglish: ['kappal', 'ship', 'kappl'], english: 'ship', category: 'objects', difficulty: 'easy' },
  { id: 'train', tamil: 'ரயில்', tanglish: ['rayil', 'train', 'rail', 'rayill'], english: 'train', category: 'objects', difficulty: 'easy' },
  { id: 'airplane', tamil: 'விமானம்', tanglish: ['vimaanm', 'vimaanam', 'plane', 'plane'], english: 'airplane', category: 'objects', difficulty: 'easy' },
  { id: 'kite', tamil: 'பட்டம்', tanglish: ['pattam', 'kite', 'pattm'], english: 'kite', category: 'objects', difficulty: 'easy' },
  { id: 'ball', tamil: 'பந்து', tanglish: ['panthu', 'ball', 'bandu', 'pandu'], english: 'ball', category: 'objects', difficulty: 'easy' },
  { id: 'candle', tamil: 'மெழுகுவர்த்தி', tanglish: ['mezhuguvartthi', 'candle', 'mezhugevarthi'], english: 'candle', category: 'objects', difficulty: 'hard' },
  { id: 'bucket', tamil: 'வாளி', tanglish: ['vaali', 'bucket', 'valli'], english: 'bucket', category: 'objects', difficulty: 'easy' },

  // ═══════════════════ இயற்கை (Nature) ═══════════════════
  { id: 'rain', tamil: 'மழை', tanglish: ['mazhai', 'malai', 'rain', 'maazhai'], english: 'rain', category: 'nature', difficulty: 'easy' },
  { id: 'sun', tamil: 'சூரியன்', tanglish: ['suriyan', 'sooryan', 'sun', 'suuriyan'], english: 'sun', category: 'nature', difficulty: 'easy' },
  { id: 'moon', tamil: 'நிலவு', tanglish: ['nilavu', 'nilaavu', 'moon', 'nillavu'], english: 'moon', category: 'nature', difficulty: 'easy' },
  { id: 'star', tamil: 'நட்சத்திரம்', tanglish: ['natchathiram', 'star', 'nakshatram'], english: 'star', category: 'nature', difficulty: 'medium' },
  { id: 'mountain', tamil: 'மலை', tanglish: ['malai', 'mountain', 'malli'], english: 'mountain', category: 'nature', difficulty: 'easy' },
  { id: 'sea', tamil: 'கடல்', tanglish: ['kadal', 'sea', 'ocean', 'kadall'], english: 'sea', category: 'nature', difficulty: 'easy' },
  { id: 'river', tamil: 'நதி', tanglish: ['nathi', 'river', 'nadhi'], english: 'river', category: 'nature', difficulty: 'easy' },
  { id: 'sky', tamil: 'வானம்', tanglish: ['vaanam', 'sky', 'vanam'], english: 'sky', category: 'nature', difficulty: 'easy' },
  { id: 'cloud', tamil: 'மேகம்', tanglish: ['megam', 'cloud', 'megham'], english: 'cloud', category: 'nature', difficulty: 'easy' },
  { id: 'wind', tamil: 'காற்று', tanglish: ['kaatru', 'kaatu', 'wind', 'kaattu'], english: 'wind', category: 'nature', difficulty: 'easy' },
  { id: 'fire', tamil: 'நெருப்பு', tanglish: ['neruppu', 'nerppu', 'fire', 'nerp'], english: 'fire', category: 'nature', difficulty: 'easy' },
  { id: 'flower', tamil: 'பூ', tanglish: ['poo', 'pu', 'flower', 'poov'], english: 'flower', category: 'nature', difficulty: 'easy' },
  { id: 'leaf', tamil: 'இலை', tanglish: ['ilai', 'elai', 'leaf', 'illai'], english: 'leaf', category: 'nature', difficulty: 'easy' },
  { id: 'soil', tamil: 'மண்', tanglish: ['mann', 'man', 'soil', 'mannu'], english: 'soil', category: 'nature', difficulty: 'easy' },
  { id: 'wave', tamil: 'அலை', tanglish: ['alai', 'wave', 'allay'], english: 'wave', category: 'nature', difficulty: 'easy' },
  { id: 'rainbow', tamil: 'வானவில்', tanglish: ['vaanavil', 'rainbow', 'vaanabill'], english: 'rainbow', category: 'nature', difficulty: 'medium' },
  { id: 'lightning', tamil: 'மின்னல்', tanglish: ['minnal', 'lightning', 'minnall'], english: 'lightning', category: 'nature', difficulty: 'easy' },
  { id: 'snow', tamil: 'பனி', tanglish: ['pani', 'panee', 'snow'], english: 'snow', category: 'nature', difficulty: 'easy' },

  // ═══════════════════ உடல் (Body) ═══════════════════
  { id: 'hand', tamil: 'கை', tanglish: ['kai', 'hand', 'kaii'], english: 'hand', category: 'body', difficulty: 'easy' },
  { id: 'leg', tamil: 'கால்', tanglish: ['kaal', 'leg', 'kal', 'kaall'], english: 'leg', category: 'body', difficulty: 'easy' },
  { id: 'head', tamil: 'தலை', tanglish: ['thalai', 'talai', 'head', 'thali'], english: 'head', category: 'body', difficulty: 'easy' },
  { id: 'eye', tamil: 'கண்', tanglish: ['kann', 'kan', 'eye', 'kaan'], english: 'eye', category: 'body', difficulty: 'easy' },
  { id: 'nose', tamil: 'மூக்கு', tanglish: ['mukku', 'mookku', 'nose', 'muuku'], english: 'nose', category: 'body', difficulty: 'easy' },
  { id: 'mouth', tamil: 'வாய்', tanglish: ['vaai', 'mouth', 'vaay', 'vai'], english: 'mouth', category: 'body', difficulty: 'easy' },
  { id: 'ear', tamil: 'காது', tanglish: ['kaathu', 'ear', 'kathu', 'kaatu'], english: 'ear', category: 'body', difficulty: 'easy' },
  { id: 'hair', tamil: 'முடி', tanglish: ['mudi', 'muddi', 'hair', 'moodi'], english: 'hair', category: 'body', difficulty: 'easy' },
  { id: 'teeth', tamil: 'பல்', tanglish: ['pal', 'pall', 'teeth', 'pallu'], english: 'teeth', category: 'body', difficulty: 'easy' },
  { id: 'tongue', tamil: 'நாக்கு', tanglish: ['naakku', 'tongue', 'nakku'], english: 'tongue', category: 'body', difficulty: 'easy' },
  { id: 'finger', tamil: 'விரல்', tanglish: ['viral', 'finger', 'virall'], english: 'finger', category: 'body', difficulty: 'easy' },
  { id: 'heart', tamil: 'இதயம்', tanglish: ['idhayam', 'heart', 'idhayam'], english: 'heart', category: 'body', difficulty: 'easy' },
  { id: 'stomach', tamil: 'வயிறு', tanglish: ['vayiru', 'stomach', 'vairu', 'vayiru'], english: 'stomach', category: 'body', difficulty: 'easy' },
  { id: 'shoulder', tamil: 'தோள்', tanglish: ['thol', 'shoulder', 'tool'], english: 'shoulder', category: 'body', difficulty: 'easy' },
  { id: 'knee', tamil: 'முழங்கால்', tanglish: ['muzhangkaal', 'knee', 'muzhankal'], english: 'knee', category: 'body', difficulty: 'medium' },
];

export const CATEGORIES = [
  { id: 'all', label: 'அனைத்தும்', emoji: '🎲' },
  { id: 'animals', label: 'விலங்குகள்', emoji: '🦁' },
  { id: 'food', label: 'உணவு', emoji: '🍛' },
  { id: 'objects', label: 'பொருட்கள்', emoji: '🏠' },
  { id: 'nature', label: 'இயற்கை', emoji: '🌿' },
  { id: 'body', label: 'உடல்', emoji: '✋' },
];

export function getRandomWords(category = 'all', count = 3) {
  const pool = category === 'all' ? WORDS : WORDS.filter(w => w.category === category);
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export function getWordById(id) {
  return WORDS.find(w => w.id === id);
}
